-- SQLBook: Code
-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.detail
(
    detail_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    todo_list_id integer NOT NULL,
    description character varying(280) COLLATE pg_catalog."default",
    CONSTRAINT detail_id PRIMARY KEY (detail_id)
);

CREATE TABLE IF NOT EXISTS public.todo_list
(
    todo_list_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    utilisateur_id integer NOT NULL,
    list_title character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT list_id PRIMARY KEY (todo_list_id)
);

CREATE TABLE IF NOT EXISTS public.utilisateur
(
    nom character varying(50) COLLATE pg_catalog."default",
    prenom character varying(50) COLLATE pg_catalog."default",
    utilisateur_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    utilisateur_mail character varying(250) COLLATE pg_catalog."default" NOT NULL,
    utilisateur_mdp character varying(250) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT utilisateur_id PRIMARY KEY (utilisateur_id),
    CONSTRAINT utilisateur_mail UNIQUE (utilisateur_mail)
);

ALTER TABLE IF EXISTS public.detail
    ADD CONSTRAINT todo_list_id FOREIGN KEY (todo_list_id)
    REFERENCES public.todo_list (todo_list_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS get_fk
    ON public.detail(todo_list_id);


ALTER TABLE IF EXISTS public.todo_list
    ADD CONSTRAINT utilisateur_id FOREIGN KEY (utilisateur_id)
    REFERENCES public.utilisateur (utilisateur_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS create_fk
    ON public.todo_list(utilisateur_id);

END;